import './globals.css'
import { Kanit } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import NavBar from '@/components/navBar/NavBar'
import { Providers } from '@/components/Provider/Provider'


const kanit = Kanit({ subsets: ['latin'], weight: ["300"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${kanit.className} bg-default transition-all duration-300`}>
        <Providers>
          <NavBar />
          {children}
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  )
}
